### ISSUE TITLE
Related work - initial review

### ISSUE THREAD

**Issue by svacina** [cloudhubs/logscraper#1]
* propose on "Github wiki" a list of publications, academic papers... related to log analysis and log scraping
* for each source describe in few sentences main thoughts that are relevant for us
* estimated duration: 1 hour

**Comment by Connor-woodahl** [comment]
Links and summaries of tools and papers under the wiki page Research Links

**Comment by tomas-cerny** [comment]
I suggest making this private as we want to write a paper about it, how about MS teams page?

**Comment by svacina** [comment]
Related work review moved to MS Teams.
