### ISSUE TITLE
Endpoint for aggregator logs

### ISSUE THREAD

**Issue by MarkFuller1** [cloudhubs/logscraper#137]
There is an endpoint to retrieve  just the pipeline logs but not just aggregator.

**Comment by Connor-woodahl** [comment]
Will resolve this today

**Comment by Connor-woodahl** [comment]
@MarkFuller1

**Comment by Connor-woodahl** [comment]
Now committed into master. The homepage of the webserver will have the path. But also for reference, '/logs/aggregate'. @MarkFuller1
