### ISSUE TITLE
Unescaped quotation in Aggregator logs

### ISSUE THREAD

**Issue by JacksonRaffety** [cloudhubs/logscraper#18]
aggregator1.log and aggregator2.log contain unescaped quotation marks in their message that make JSON decoding impossible. These unescaped quotation marks appaer in lines 8 and 9 of each. A temporary fix is to skip the first few lines of the file, but this is not optimal.

**Comment by tisnik** [comment]
Ah yes, I'll fix it, the problem is on input side.
