### ISSUE TITLE
Some Logs without organization and cluster_id

### ISSUE THREAD

**Issue by JacksonRaffety** [cloudhubs/logscraper#19]
Consumed log records can sometimes not include the organization or cluster_id when an error occurs. 

Example is lines 18-23 in aggregator.log
![image](https://user-images.githubusercontent.com/46944575/83051134-6a2e0100-a002-11ea-835e-8e6bd72533a3.png)

**Comment by svacina** [comment]
@JacksonRaffety 
Yes, some logs does not have organization and cluster id, it is going to be our task to identify, why they do not have and associate them with some cluster id and organization.
