### ISSUE TITLE
RFE: ability to retrieve logs directly from OpenShift

### ISSUE THREAD

**Issue by tisnik** [cloudhubs/logscraper#28]
Might be implemented as a separate script

**Comment by svacina** [comment]
We have couple of questions:
* How to connect to open shift instance?
* Is there a guide of connecting python to open shift?

**Comment by svacina** [comment]
@tisnik 

Can we use this connector to open shift?
https://github.com/openshift/openshift-client-python

**Comment by svacina** [comment]
@tisnik 

Are we going to connect to an instance of OpenShift running at RedHat?

**Comment by tisnik** [comment]
It would be possible either to use `oc` client or the Python client you mentioned. I'm about to ask for OpenShift account for you.

**Comment by svacina** [comment]
@tisnik 
Ok, can we call over MSTeams?

**Comment by svacina** [comment]
Not relevant any more, we use Kafka now.
