### ISSUE TITLE
Propose representation of error log item as json object

### ISSUE THREAD

**Issue by svacina** [cloudhubs/logscraper#3]
Something like this:

{
   "date":"",
   "line of code":"",
   "file name":"",
}

**Comment by tomas-cerny** [comment]
Perhaps to add a "host"? in case it is distributed file name can be the same?

**Comment by JacksonRaffety** [comment]
{
"date/time":"",
"level/type":"",
"message":"",
"file":"",
"line":"",
"thread-id":"",
"process-id":"",
"machine/host":"",
"component":"",
"context":""
}
