### ISSUE TITLE
Script to satisfy Issue 30

### ISSUE THREAD

**Issue by Connor-woodahl** [cloudhubs/logscraper#41]
Will need at least two different functions.

**Comment by brooklynnStone1** [comment]
Object returned will contain: 
- timestamp
- status ("found" if the chunk was found, "warning" if the associated logs are a warning, and "error" if the associated logs are an error)
- description (the array of all the messages associated with the chunk)

There will be two options, both will be given the directory to search from:
- Search by org_id and cluster_name: cluster_name will be found first then verified that the org_id matches
- Search by offset: offset is unique in aggregator logs but the offsets in pipeline repeat all over. Searching for offsets may only be applicable to aggregator logs. 
@tisnik what do you think?
