### ISSUE TITLE
status of org_id and cluster_name

### ISSUE THREAD

**Issue by svacina** [cloudhubs/logscraper#47]
* develop script for "what's the status of results for org_id=42 and cluster_name=ffff0000....?"

**Comment by Connor-woodahl** [comment]
Object returned will contain:

timestamp
status ("found" if the chunk was found, "warning" if the associated logs are a warning, and "error" if the associated logs are an error)
description (the array of all the messages associated with the chunk)

Search by org_id and cluster_name: cluster_name will be found first then verified that the org_id matches

**Comment by Connor-woodahl** [comment]
In #30
