### ISSUE TITLE
develop script to find message with offset in the aggregator

### ISSUE THREAD

**Issue by svacina** [cloudhubs/logscraper#48]
referencing to issue #30 

"was the message with offset=1234 properly processed and stored into aggregator?"

**Comment by Connor-woodahl** [comment]
Object returned will contain:

timestamp
status ("found" if the chunk was found, "warning" if the associated logs are a warning, and "error" if the associated logs are an error)
description (the array of all the messages associated with the chunk)

**Comment by JacksonRaffety** [comment]
We should consider having a generic "Problem" flag that is set if Warning or Error are associated to provide for quick determining of which matches are worth examining.
