### ISSUE TITLE
OpenAPI specification for REST API endpoints

### ISSUE THREAD

**Issue by tisnik** [cloudhubs/logscraper#51]
It's an usual requirement for customer facing APIs to provide OpenAPI specification with description of all REST API endpoints. Using OpenAPI 3.0 brings us some beneftis. Such as an autogenerated client; it will be useful in testing.

## Acceptance criteria:

- In case the API needs to be re-designed, that's not within scope of this task
- Assuming the API is fine (one endpoint right now), the desired output is JSON specification that describes the API

**Comment by svacina** [comment]
We are not going to use the webserver in production.
