### ISSUE TITLE
Process aggregation.log

### ISSUE THREAD

**Issue by svacina** [cloudhubs/logscraper#7]
* derive organization and cluster id
* include messages into a string array
* in case of error, include all following messages to previous record
* produce array of objects where each object is uniquely identified by offset and has an array of messages

**Comment by JacksonRaffety** [comment]
In the aggregator.log files, I have found there to be 3 general types of groupings, type Consumed, type Request URI, and type Consumed Message offset. In type Consumed, there is an associated organization and cluster to group the logs by, but for the other two types, there isn't a clear way to group, other than hard-code the parse. Are we only concerned with the 'Consumed' type (found in the first 1,000 lines of aggregator.log)?

**Comment by svacina** [comment]
Let's reasonably group also the other types. I will let you decide on the format of other types.
