### ISSUE TITLE
Process pipeline.log

### ISSUE THREAD

**Issue by svacina** [cloudhubs/logscraper#8]
* derive organization and cluster id
* include messages into a string array
* in case of error, include all following messages to previous record
* produce array of objects where each object is uniquely identified by orgnization and cluster id and has an array of messages

**Comment by brooklynnStone1** [comment]
@tisnik I was looking through the log file with Jan and noticed that there is a Partition number and Offset number. What are these numbers indicating and is there a way we can use these to group log messages together?

**Comment by svacina** [comment]
@brooklynnStone1 Let's push this issue to finsih as soon as possible. It needn't to be perfect, any reasonable output will do at current stage.
