### ISSUE TITLE
example of log transformation into pages

### ISSUE THREAD

**Issue by svacina** [cloudhubs/logscraper#90]
Acceptance criteria:

* chunk of raw logs from pipeline and aggregator and the result

**Comment by JacksonRaffety** [comment]
Gave two examples for aggregator, one for pipeline

**Comment by svacina** [comment]
It should be markdown, .md, not pdf.
Place all the information in the pdf to .md

https://github.com/cloudhubs/logscraper/blob/master/docs/Transformations.pdf

Delete the pdf after that.

**Comment by svacina** [comment]
Please, update also the main docu page: https://cloudhubs.github.io/logscraper/ so it includes link to that .md file
